#!/usr/bin/env bash

set -e

cd $(dirname $0)/..

echo Running format...

PACKAGES=". $(find . -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

go fmt ${PACKAGES}
