#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG="latest"
REPO=panamax.spectrumxg.com/star-dev

cp ../bin/external-dns .

IMAGE=${REPO}/external-dns:${TAG}
docker build -t ${IMAGE} .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
