#!/usr/bin/env bash

set -e

#
# This script has a new debug usage.
# Simply call `bash scripts/test -v` (notice the `-v`) for debug.
#

cd $(dirname $0)/..

echo Running tests...

PACKAGES=". $(find . -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

[ "${ARCH}" == "amd64" ] && RACE=-race

# flags
case "$1" in
  -v)
    DEBUG=-v
    ;;
esac

go test ${DEBUG} ${RACE} -cover -tags=test ${PACKAGES}
